apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 443
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-ssl-volume
          mountPath: /etc/nginx/ssl
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
    - name: nginx-ssl-volume
      secret:
        secretName: nginx-tls-secret
